### ISSUE TITLE
Act as URL handler for stream and clip links

### ISSUE THREAD

**Issue by imarko** [twireapp/Twire#11]
Would be nice if Twire could act as a URL handler for various twitch link types.

The essential ones:

1. Channel link. Would expect it to open the current live stream on the channel. Example: https://www.twitch.tv/starcraft/
2. Clip link. Would expect it to play the clip in question. Example: https://www.twitch.tv/starcraft/clip/JollyPrettyGnatAliens

**Comment by samfundev** [comment]
Since Twire doesn't currently support clips I've not added handling for them but I did add support for both streams and VODs. I've opened another issue (#130) for adding clip support.
