### ISSUE TITLE
Twire BTTV Emotes and Portrait Mode 

### ISSUE THREAD

**Issue by ACodingGenie** [twireapp/Twire#116]
First of, thank you for making such an amazing app for and a ad-free alternative to the main Twitch app. I absolutely love using the app especially on my Amazon Fire Stick which struggles with Twitch's official app but runs butter smooth with Twire on 1080P 60FPS. 
Now with the issue, in one of the recent updates, I've noticed that all of the animated BTTV emotes are not working anymore. In chat you simply see text but they are not being rendered. For example you will see, "PepeJAMJAM" or something equivalent instead of the actual animated GIF of the emote. The second issue is, in Portrait mode on Android, when you open up any stream, the stream player is extremely squished and covers about 10-20% of the actual screen from the top. The rest is taken up by the chat. However, the landscape mode works perfectly without a problem. The BTTV emote problem still persists regardless.
Thank you kindly.

|--------------------------|
|   Actual video (20%)     |  <--This is extremely squished unlike before the updates.
|_________________________|
|               -                     |
|      CHAT (80% ish)       |
|                  -                  |
...                                    |
|_________________________|

**Comment by samfundev** [comment]
Thanks for the report, could you clarify some things for me:
 - Are you using the latest version of the app? (Version 2.519)
 - What device are you using?
 - What version of Android are you using?

**Comment by ACodingGenie** [comment]
So the BTTV animated emote problem seems to have been resolved in the new update. I hadn't realized there was a new update until after I had posted about the issue which fixed it, so I apologize for that. As for the portrait orientation problem, it is ALSO FIXED on my Samsung Galaxy S6. BTW do you read minds or something lol? 

On a side note, if it helps anyone that runs Blokada ad blocker on their phone like I do, false positives in the DDG Tracker radar hosts list is apparently blocking features in the Twire app. BTTV emotes, streams not _loading...etc..etc... maybe_ a result of using that list.

Thank you getting back so fast, I appreciate it. BTW are you signed up as a creator on Brave Rewards? I would love to donate a certain amount of BAT Tokens every month for your amazing effort for building this app. Cheers!

**Comment by samfundev** [comment]
I'm glad everything's resolved.I signed up as a creator and tied it to my GitHub. I don't know much about how the program works but if you'd like to donate to me, I appreciate it.
