### ISSUE TITLE
RSS Subscription with Export/Import

### ISSUE THREAD

**Issue by seniorm0ment** [twireapp/Twire#124]
It would be absolutely amazing to be able to subscribe without an account, similar to how Newpipe does it. RSS subscriptions, with the ability to export/import your RSS subscription list or easy migration/reinstalls. Would be great if it can also work with live notifications.

**Comment by samfundev** [comment]
Thanks for the suggestion. I'm just gonna mention issue #81 as these two issues are related.

**Comment by grravity** [comment]
Ah, very nice, hope to see this implemented

**Comment by samfundev** [comment]
I believe this issue is closed by https://github.com/twireapp/Twire/pull/240. It is now possible to import and export a copy of the streamers you follow. Please let me know if this issue isn't resolved.
