### ISSUE TITLE
Support for Android TV remote control on Xiaomi Mi Box

### ISSUE THREAD

**Issue by JoeGold12** [twireapp/Twire#125]
Hello, thanks for the great app. Is it possible to add remote control support for Android TV? I'm using a Xiaomi Mi Box S with Android TV 9. It would be great to have an alternative to the standard twitch app on my TV. (The app NewPipe from the f-droid store works fine with the remote, would be awesome if Twire could too).

Thanks

**Comment by samfundev** [comment]
I'm going to close this as a duplicate of #121 as I suspect once I get this working for an Amazon Fire it should work with Android TV. Please let me know if it doesn't work once I get that working.
