### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by UltraBlackLinux** [twireapp/Twire#126]
So Im getting this "Oops, Twitch's servers dont seem to respond, Refresh?" error when pressing on "My streams" and when pressing on a deatured stream, Twire always fails to connect to the chat.
The log also doesnt seem to say anything useful.
Is there any fix for that?

**Comment by codewizkid** [comment]
> So Im getting this "Oops, Twitch's servers dont seem to respond, Refresh?" error when pressing on "My streams" and when pressing on a deatured stream, Twire always fails to connect to the chat.
> The log also doesnt seem to say anything useful.
> Is there any fix for that?

I've been having the same issue for a few days now. Is their an ETA on a fix for this?

**Comment by samfundev** [comment]
Sometimes Twitch invalidates your login and you need to login in again. Twire is supposed to tell you if you need to do that and I thought I fixed it but it's actually not working correctly. Sorry about that. I was able fix this and can confirm it's working correctly. It should be out in the next version of Twire. For now, login again and it should work.
