### ISSUE TITLE
Twire goes back to main screen after closing PiP player

### ISSUE THREAD

**Issue by Nextross** [twireapp/Twire#127]
After closing PiP, Twire goes back to the previous screen. Happens everytime, this is how I replicate it:

1. Open Twire
2. Selec a stream (doesn't matter which)
3. Click home button on my phone (or select different app that is already opend) - the PiP window will appear
4. After clicking the X button on the PiP window, Twire goes back to 'My streams' screen (selected by me to open first after start up)

**Comment by PacoBell** [comment]
Isn't that expected behavior? The 'X' signifies intent to close the stream. If you wanted to return to full screen, you should have tapped on the expand button instead.

**Comment by samfundev** [comment]
Unless I misunderstanding, this is how I would expect it to work. Closing PIP should go to the previous screen and expanding should reopen the player.
