### ISSUE TITLE
System UI covers chat in landscape mode when compose box is tapped

### ISSUE THREAD

**Issue by Skirmisher** [twireapp/Twire#13]
With a physical keyboard, the navigation bar has no business showing up when the chat box is focused. It covers the send button, among other things, making the lack of #12 more problematic.

However, the chat box seems to remain focused after tapping another UI element, even without intentionally focusing it at all, so it is still possible to type in chat in landscape without this issue occurring.

**Comment by samfundev** [comment]
I cannot reproduce this issue. This is what I see when tapping on the compose box:
![image](https://user-images.githubusercontent.com/6759716/177018787-6020b54a-1061-418c-a6d4-2bbbbf18f026.png)
Android 12, 6636df93b74090e330ff06c0f40e36b42fdd5fd8
