### ISSUE TITLE
ads / comercial break 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [twireapp/Twire#132]
api twitch some modified before some stream comercial break display need wait 14 second for display streamers 

thanks

**Comment by samfundev** [comment]
Sorry, I'm having trouble understanding what you're saying. Are you trying to say that Twire should wait 14 seconds before it displays the stream when there is a commercial break?

**Comment by samfundev** [comment]
Wait, I'm confused. Isn't this the same thing as #85?

**Comment by Disqu3-mirOir-qt** [comment]
![Screenshot_20200911-183348](https://user-images.githubusercontent.com/41585567/92950739-caff0f00-f422-11ea-93d0-007cb1bddb00.jpg)

**Comment by Disqu3-mirOir-qt** [comment]
when get .m3u in network log , and open in browser don,t see this , maybe can provide by  .ts but not sure

**Comment by samfundev** [comment]
Sorry, I understand what you're talking about now. I'm going to mark this a duplicate of #85 since they're both about the same problem.
