### ISSUE TITLE
Top streams and games now only show streams in your system language.

### ISSUE THREAD

**Issue by complainer123** [twireapp/Twire#133]
nice thought but as non english native speaker 4/5 of the streams I watch are not 'visible' anymore. Can you consider an option in settings where I can specify different languages?

**Comment by samfundev** [comment]
The next version of Twire is going to have an option to disable that functionality. Would that be good or would you want to be select exactly what languages you want to see?

**Comment by complainer123** [comment]
I looked through the issues (#120 #23 #52  and #104) to get a better perspective and from what i saw a toggle would be fine. Of course a language filter for multiple languages would be a good feature to play around with. But if its to much trouble I'm fine with the toggle.

**Comment by samfundev** [comment]
I think I'll close this issue and open another about being able to pick multiple languages. As I suspect there has got to be some people out there who are multilingual and would like to see streams in the languages that they speak.
