### ISSUE TITLE
Crowdin/Weblate translate support

### ISSUE THREAD

**Issue by RickyM7** [twireapp/Twire#138]
Do you plan to put your project on some of these sites to give more support to anyone who wants to help with translation? I want to translate this app to pt-BR and with the tools and organization of these sites everything is faster and easier.

**Comment by samfundev** [comment]
Thanks for the suggestion, I didn't realize these services offered plans for open source projects. I've created a project on Weblate: https://hosted.weblate.org/projects/twire/. I've never used one of these services before so if you have any suggestions, feel free to let me know.

**Comment by RickyM7** [comment]
Of course, thank you very much for that.

**Comment by RickyM7** [comment]
@samfundev In fact, when you have time, add this link to the README for others to see and help with the translation.  You could also add it to the app somewhere, for example in "About", above or below "Settings", there you can add the GitHub link, the Weblate link and the open source licenses you use in the app.
