### ISSUE TITLE
Changelog "Done" button disabled on 2.9.0

### ISSUE THREAD

**Issue by Porkepix** [twireapp/Twire#143]
Issue was encountered on both an Android 6 and an Android 10, after updating the application from F-droid, I had to log in again, and after that got the changelog screen. I had to use the system return button because the "done" button was, as visible on the screenshot below, grayed out and disabled.

![Screenshot_20201013-132743](https://user-images.githubusercontent.com/709500/95855376-956a8000-0d58-11eb-92e4-acc22a138cfb.png)

**Comment by samfundev** [comment]
This has been fixed by a184ca20842752f3c882a2b8f81fa1ce8ea3bde8.
