### ISSUE TITLE
Every click in the menus open a new view

### ISSUE THREAD

**Issue by Porkepix** [twireapp/Twire#145]
Every single click in the menu seems to create a new view instead of redrawing the current one. This means, for example, that if user want to go back to the homescreen with the return/precedent button, user will need to tap that button as many times as he used the menu.
Menu should just redraw current screen/context instead of creating a new one over the current one.

EDIT: Also clicking return/precedent too quickly many times result in the application being too slow to get back to the preview view, so it redraws the same and leads to infinite redraw of the same view.

**Comment by samfundev** [comment]
Sorry, I'm confused. The point of the back button in Android is to back to the previous screen. If you want to back to Android's homescreen with all the apps, you should use the home button. If you want to go to a certain screen, you should use the hamburger menu in the top left. This is how I believe most apps handle this.

**Comment by samfundev** [comment]
Closing to due lack of information.

**Comment by Porkepix** [comment]
> Closing to due lack of information.

What do you want as additional information? Or what do I need to explain in a better way?

**Comment by samfundev** [comment]
> Sorry, I'm confused. The point of the back button in Android is to back to the previous screen. If you want to back to Android's homescreen with all the apps, you should use the home button. If you want to go to a certain screen, you should use the hamburger menu in the top left. This is how I believe most apps handle this.

What are you requesting that can't be handled by using Android's home button or hamburger menu? Or are you requesting that the hamburger menu should be available in more views?

**Comment by Porkepix** [comment]
I'll wait for next release available on F-droid to get a look at how it behave now, thanks for looking at it!
