### ISSUE TITLE
Make it so you can use Twire without chat? 

### ISSUE THREAD

**Issue by HTSamurai** [twireapp/Twire#149]
I don't know if there is a way to stop seeing chat in the app, but on Twire could you add a "Show chat in vertical" tickbox in the Chat settings? Thanks! 

If there is a way to do this please tell me.
I am fine if it requires editing my twitch account settings.

**Comment by samfundev** [comment]
You can hide the chat when the device is horiztonal by clicking the arrow on the right side of the interface. But if the device is vertical, there's no way to hide the chat. Are you asking for a way to hide the chat when the device is vertical?

**Comment by HTSamurai** [comment]
Yes, but nevermind. I don't see why i would need vertical. It would be cool if it showed a next streams thing. But nevermind.
