### ISSUE TITLE
Czech translation is finished

### ISSUE THREAD

**Issue by Nextross** [twireapp/Twire#153]
I finished the tranlation, you can check it if everything's alright :)

**Comment by samfundev** [comment]
I don't speak Czech but it's all translated and there's no checks in Weblate. I'll be adding the new languages in the next release of Twire. Thanks for helping out with translating.

**Comment by Nextross** [comment]
After the next release I'll try to check everything again, because some sentences are different in different context, so there might be small mistakes.
