### ISSUE TITLE
user crt trust

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [twireapp/Twire#156]
please twire can trust user certificat , 

now twire can,t trust and reduced my adblocker capacity 

thanks

**Comment by samfundev** [comment]
Sorry, I don't know what you're trying to ask.

**Comment by Perflyst** [comment]
I think he wants to MITM the connection between his phone (Twire) and Twitch.

@Disqu3-mirOir-qt you should be able to install your self signed certificate in the trust store of your android phone. This is definitely out of scope for Twire
