### ISSUE TITLE
Background Audio, VOD Speed, Bitrate

### ISSUE THREAD

**Issue by lsafd** [twireapp/Twire#160]
I just want to start by saying that the issues listed in the title may seem different, but fixing some of them would make fixing others unnecessary, so I have included all of them in one post (Sorry it's long).

I love the app and have looked through other issues to make sure this is not repetitive (There is another issue that talks about background audio, but this is significantly different).

### My Problem:

I want to listen to audio content on Twire (mostly in the form of VODS). However, 
* Twire doesn't support audio only playback 
* Twire doesn't support changing playback speed on VODS
* When using an external player to fix other issues the bitrate is very high (No matter the orignial quality settings in Twire the birate for the external player is about equivalent to auto or source quality within Twire. It seems most likley to me that the external player is handed a stream with different quality settings than the ones in use in Twire when "Use external player" is selected.)

I will propose two possible solutions to the problems as I see them and go into more detail.

### Why it is Relevant and Important:

Just chatting and audio content in general is arguably the largest single category on Twitch. These problems make it difficult to use Twire to access this content. Furthermore, fixing these issues would enhance viewing for other forms of content too (Speed up slow parts of a speedrun, play in background when doing something else to catch important moments, etc.).

### Solution 1: The "Easy" Way

This solution sets out to fix the following problems:
* Bitrate issues when switching to an external player

Within Twire there are good controls for the stream quality and bitrate that seem to work. In theory fixing the handoff to an external player, so that the external player uses the correct bitrate (Which it does not seem to be doing right now), would allow users to acess any functionality that they need without having to directly incorporate it into Twire.

This way is only easy if Twitch APIs actually support it.

### Solution 2: The "Best" Way

This solution sets out to fix the following problems:
* No audio only playback in Twire
* No playback speed control for VODS in Twire

This solution could be considered "better" because it does not force users to be reliant on an external player. In addtion, the use of an external player means that users cannot take advantage of Twire's chat funcions. However, I am unsure how difficult these additions would be and it may be easier to let an external player handle background playback and speed controls.

### Conclusion:

Either of these solutions would allow me to listen to audio content on Twire without issue. I will keep an eye on this issue in case you have any questions for me and again thanks for making such a great app!

**Comment by lsafd** [comment]
If f2e096c231d2cd3f57c7829b93bc0b918740b4ba correctly describes itself then it fixes this issue. Excited for next release including this patch

**Comment by samfundev** [comment]
@lsafd I'm a bit confused. That commit just fixes a bug where qualities were not parsed correctly. So only the "Auto" quality was appearing. It doesn't add support for audio-only, which I'm guessing you might have thought it did. Twire needs to do some additional stuff to support audio-only playback.

**Comment by lsafd** [comment]
I think because this post is long it may be confusing.

As many issue threads and my "Solution 1" bring up, external players provide support for audio-only playback with Twire. However, the one problem was the bitrate which was extremely high due to the aforementioned "Auto" quality bug (Which is directly mentioned in this issue) (Maybe this issue should have been marked as bug not enhancement, my bad because I was unsure if it ever worked the way I proposed). 

With the new commit, I should be able to select the lowest quality, use an external player for audio-only playback, and get audio-only playback with a bitrate at least similar to native audio only.

"Solution 2" is about native audio only playback, but is somewhat redundant if "Solution 1" is implemented.
