### ISSUE TITLE
Can´t watch any content at all

### ISSUE THREAD

**Issue by MarcoWilli** [twireapp/Twire#168]
Must be since last update 2.9.1.
Before I was using the app regularly with nearly no issue ("My Games" doesn´t work since a while).

Now neither VoDs nor streams will play. 
Getting message "VoD/Stream not could not be played. Try a different quality" (translated from German).

Chat seems to work fine, though.

Using LineageOS 14.1 (Android 7.1.2) on a Sony Xperia Z5 Compact.
If I can give you more technical information please tell me how to.

**Comment by GithubOwly** [comment]
Same problem here and getting same error message,
started with the 2.9.1 update.

Android 10

**Comment by MrTeeXD** [comment]
I am experiencing the same issue

**Comment by Kodionpi** [comment]
The same with me. I downgraded to 2.9.0 and now it works like before.

**Comment by ikrevem** [comment]
This is odd, I installed the latest update (2.9.1) and it works just fine for me 🤔
I can play both live streams and VODs without errors.

Anyway, I confirm the issues with "My Games" not loading.

Android 11

**Comment by Fakeacc-user** [comment]
Same problem here. I uninstalled and reinstalled from f-droid and it works again. So maybe don´t only update. The issue now is that i don´t have Quality Settings. Only Auto is available. Checked some big and small streamers. Not so big Issue. Auto is mostly fine.

**Comment by rommor19** [comment]
I guess it may have to do with Amazon changing how ads are fetched (? I installed 2.9.1 and it outright didn't work, I couldn't played anything, got the same error describe in here, not even after resetting cache and app data. Then I moved back to 2.9.0 and it has been working fine except that one-time I got the error mid-stream, I closed and reopened the app and it continued working.

**Comment by samfundev** [comment]
I can only reproduce the issue where streams just have the Auto quality option and I have been able to fix that bug. I am wondering if fixing that bug would also fix not being able to watch any content at all. [Here is a build](https://github.com/twireapp/Twire/files/5700546/Twire.zip) and if someone could try it out and let me know if that fixes the issue, I would appreciate it.

**Comment by rommor19** [comment]
It has been working great so far! Content plays normally and can change  vod quality without any problem. Let's wait for some more feedback if you want.

**Comment by samfundev** [comment]
@rommor19 Thanks for letting me know. I'm going to wait until tomorrow and then I'll release the build. I feel like if it's been solving problems for you and RickyM7 with #170 then I think it would be good to get a new release out.
