### ISSUE TITLE
Streams quality can not be changed

### ISSUE THREAD

**Issue by RickyM7** [twireapp/Twire#170]
From v2.9.1 only the quality "Auto" is available in the quality options. This did not occur in v2.9.0.

Device: Redmi Note 4 (MIUI 11 - Android 7.0)
App version: v2.9.1

**Comment by samfundev** [comment]
I am only able to reproduce this behavior for streams. Could you let me know if fixing that also fixes this issue for you? I've included a build in [this comment](https://github.com/twireapp/Twire/issues/168#issuecomment-745777054) which you can try out.

**Comment by RickyM7** [comment]
@samfundev Everything working perfectly in this build, both this and the issue #168 (which was occurring with me as well) were fixed.
Thank you so much for working so fast on a fix for this.
