### ISSUE TITLE
Update ExoPlayer to 2.12.3

### ISSUE THREAD

**Issue by TacoTheDank** [twireapp/Twire#175]
From https://github.com/twireapp/Twire/pull/172#issuecomment-748529980

ExoPlayer [2.12.2](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md) gives us three deprecations in the code, and they have to do with the second bullet point in the UI section of the changelog.

ExoPlayer 2.12.3 is just a bugfix release.

**Comment by roshavagarga** [comment]
Update: 2.12.3 is out.

**Comment by TacoTheDank** [comment]
Yay!
