### ISSUE TITLE
2.9.2 App fails to stay logged in between relaunches

### ISSUE THREAD

**Issue by dankxylese** [twireapp/Twire#176]
Not sure why it's happening, but every time I launch the app it signs me out of twitch and forces me to re login. Not sure how to log it, if it's even possible, but having to wait for a code to be sent to my email every time I sign in makes its very hard to use.

I'm happy to assist in any way I can. I'm currently rooted on Android 10

**Comment by micwoj92** [comment]
Same here, android 9, EMUI 9.1, non rooted

**Comment by rommor19** [comment]
Same here, LG Android 10, non-rooted.

It appears that the session token is not being properly stored because every time I re-login, I can see the interface preferences I've previously set.

**Comment by dankxylese** [comment]
Just to add this is on the latest version 2.9.2

**Comment by Ud4ba** [comment]
this happens more times when i kill the app .

**Comment by dankxylese** [comment]
> this happens more times when i kill the app .
That's exactly the bug. When the app gets closed it doesn't save log on data properly.

**Comment by samfundev** [comment]
This has been fixed and will be out in a new release soon. In the meantime, you can fix this issue by pressing "Skip" during the setup and then log in by going into the settings.
