### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [twireapp/Twire#179]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by roshavagarga** [comment]
Feel free to offer a pull request :)

**Comment by mondlicht-und-sterne** [comment]
The topic of PR and merge is too difficult
for me. You can, if you use Fastlane, just
add screenshots to make your app view more
beautiful. So it was just a hint that more can
be displayed - if desired.

**Comment by samfundev** [comment]
I haven't use fastlane before but I'd definitely like to add screenshots for Twire.

**Comment by sh0wst0pper** [comment]
Sorry for the off-topic reply, but how long does it take the updates to hit F-Droid normally?

**Comment by dankxylese** [comment]
> Sorry for the off-topic reply, but how long does it take the updates to hit F-Droid normally?

Depends, since as far as I know, f-droid does their own builds based on the repo. Last update took them 6 days after the release apk was posted here

**Comment by samfundev** [comment]
Added in #381
