### ISSUE TITLE
Playback Speed Modifier in Settings

### ISSUE THREAD

**Issue by V6ser** [twireapp/Twire#180]
Not really an issue, but a request.
I see that currently the only way to watch a stream in other playback speeds is through twitch.tv on desktop.
I figure exoplayer already supports this, but I don't know about Twire's implementation of it.

**Comment by samfundev** [comment]
This has been implemented as a button in the player which allows you to choose a playback speed:
![image](https://user-images.githubusercontent.com/6759716/122319985-7592e980-ceef-11eb-8910-dd923da8529f.png)
