### ISSUE TITLE
VODs not working

### ISSUE THREAD

**Issue by LukasThyWalls** [twireapp/Twire#181]
I'm using 2.9.2 (F-Droid) and yesterday i realize the VODs are not working. It said "Failed to play VOD. Try another quality" (the vod_playback_failed string) and the only option is push "Retry". A Live stream works.

I tested other Twitch apps, and Xtra devs did recently a update for Twitch API, and it works with lives and VODs. ~~In Impulse doesn't work anything (it wasn't update in two months)~~ _(EDIT: Updated today. Everything works now there)_. Maybe there is some API change what make the VODs fail in Twire.

Anyone with the same issue?

Thanks.

**Comment by mca-pro** [comment]
same issue

**Comment by mca-pro** [comment]
> I'm using 2.9.2 (F-Droid) and yesterday i realize the VODs are not working. It said "Failed to play VOD. Try another quality" (the vod_playback_failed string) and the only option is push "Retry". A Live stream works.
> 
> I tested other Twitch apps, and Xtra devs did recently a update for Twitch API, and it works with lives and VODs. In Impulse doesn't work anything (it wasn't update in two months). Maybe there is some API change what make the VODs fail in Twire.
> 
> Anyone with the same issue?
> 
> Thanks.

same issue

**Comment by drjbananas** [comment]
The VODs are also not working for me. In addition to that, the live streams aren't working either and I'm getting the same "Failed to play VOD. Try another quality" error there too. The chat works still though

**Comment by mwang99** [comment]
Also says Failed to play VOD for me too

**Comment by V6ser** [comment]
#Metoo

**Comment by QuestioningEspecialy** [comment]
This problem persists for both VODs and live streams.
> Failed to play VOD. Try another quality.
> Failed to play stream. Try another quality.
Started _maybe_ a month ago? Was originally a dice roll with whether or not it was gonna with a specific VOD/stream, and once it does it's consistent. Today, it seems to consistently happen even after a phone restart.

**Smartphone:**
 - Device: Google Pixel 6a
 - Android Version: Android 13
 - OS: GrapheneOS
 - Twire Version: 2.10.5

**Comment by LukasThyWalls** [comment]
> This problem persists for both VODs and live streams.
> 
> > Failed to play VOD. Try another quality.
> > Failed to play stream. Try another quality.
> > Started _maybe_ a month ago? Was originally a dice roll with whether or not it was gonna with a specific VOD/stream, and once it does it's consistent. Today, it seems to consistently happen even after a phone restart.
> 
> **Smartphone:**
> 
>     * Device: Google Pixel 6a
> 
>     * Android Version: Android 13
> 
>     * OS: GrapheneOS
> 
>     * Twire Version: 2.10.5

You should open a new issue as this one is old, fixed and closed.

However, it seems your issue is reported right here https://github.com/twireapp/Twire/issues/422 so better add a comment there or subscribe to that thread to keep track.
