### ISSUE TITLE
High CPU-Usage for Chat

### ISSUE THREAD

**Issue by newhinton** [twireapp/Twire#197]
The ChatManager is extremely cpu-resource hungry. It accounts to roughtly 1/3 to half of the usage of the whole app.

I measured this by opening a shell on my device and running top, htop, and reading the temperature sensors.
I used Newpipe with a random 4k 60fps video from youtube as a "baseline"

Newpipe uses roughly 60-70% with 2160p, and 65-70% with 1080p. Temperatures are rougly between 38-42°C.

The current twire release from fdroid uses roughly 100% to 180%, and the temperatures rise immediately to 67-77°C (This is not immediately warm when touching the device, but it steadily heats up until it is nearly to warm to hold). It mostly stays near 77 with occasional drops.

Profiling shows this is mostly due to calls to ChatManager.doInBackground(). Removing this call drops the cpu usage to 60-80% and temps are pretty consistent around 38-42°C.

While i have not yet found a reason why this is so cpu-heavy, this function should be improved on. Also, i recognize that those numbers are rather specific to my smartphone and may vary wildly.

**Comment by samfundev** [comment]
Thanks for letting me know. I haven't looked into the performance of Twire so I'll be sure to look into this.

**Comment by skajmer** [comment]
This is true. My phone after watching streams for longer periods of time became hot, plus there was a lot od battery getting drained. Also in extreme cases a bit laggy.

**Comment by Gnomey123** [comment]
I can 100% confirm that this is an issue.

A workaround is to select "use external player" (I've found that MPV plays the nicest with Twire).

It sucks that chat can't be disabled, like in rhynec's #303

**Comment by abhishah901** [comment]
Another workaround would be to limit how many chat messages I can go back to, some fast chats save all the messages since I start and that itself slows it down. I don't think anyone wants all the messages since they joined the chat, especially in super fasst ones

**Comment by samfundev** [comment]
@abhishah901 We currently limit to 500 messages, but we should probably lower that.
