### ISSUE TITLE
Picture-in-picture showing black screen on One UI 3.1

### ISSUE THREAD

**Issue by najodleglejszy** [twireapp/Twire#202]
Device info: Samsung Galaxy Tab S7, One UI 3.1 (Android 11)

whenever I'm watching a stream and then switch to PIP mode, the floating window becomes completely black, while the stream audio keeps playing uninterrupted. the only way to get the video back is to tap on the PIP window to temporarily increase its size by tapping on it (which seems to be a bit buggy in One UI in general, because sometimes it takes multiple taps for it to enlarge, regardless of the app using the PIP function). I've tested PIP playback with the official Twitch app as well as with VLC playing an offline video, and neither had the same issue with black screen, while I can reproduce it every single time with Twire.

**Comment by samfundev** [comment]
I've experienced this bug too, but I'm not sure what causes this to happen.

**Comment by ein-bandit** [comment]
same issue on pixel 4a Android 12.
on Android 11 i was able to click on pip, which enlarged it by a few percent and made video controls visible. This made the stream turn from black-only to the correct picture. Stream also stayed visible when clicking away and pip shrinked to original size. so i could use this "pip resize" workaround to make pip work.
Unfortunately Android 12 does not use pip resize on click.

This issue may be related to or the usage of the video playback library.

**Comment by PacoBell** [comment]
I also observe this behavior on my Pixel 6 Pro on Android 12. Resizing does indeed cause the window to start displaying properly.

**Comment by shanks1337** [comment]
I have the same issue on my Google Pixel 4a on Android 12. Resizing the window fixes this for me as well.

**Comment by samfundev** [comment]
I believe this has been fixed in 2.10.3 by e0e7c18f396aed7ab4348d7e6ccb4d3355f4d13f.
