### ISSUE TITLE
rotate when auto-rotate off.

### ISSUE THREAD

**Issue by Techwolf** [twireapp/Twire#206]
When in landscape mode on a tablet, running the program for the first time forces the table into portrait mode, making one nearly break there neck trying to use the app for the first time.

Android 9. Auto-rotate off.

**Comment by Techwolf** [comment]
Found the bug in the code. The app manifest setting needs to be changed. android:screenOrientation="portrait" to android:screenOrientation="sensor"

**Comment by Perflyst** [comment]
Feel free to submit a patch after you have tested it and it fixes your issue.

**Comment by samfundev** [comment]
This has been fixed by #210 and will be included in the next release.

**Comment by Techwolf** [comment]
Thank you Nickwasused for your time. I could not find the time to set up a dev environment for testing on my end.
