### ISSUE TITLE
Chat desync

### ISSUE THREAD

**Issue by FlaccidSnake** [twireapp/Twire#209]
Hi!
This is an error that happens fairly consistently with me and I believe it has something to do with how I watch streams exclusively over 4G, I do not have any fixed line Internet in my house; chat will appear from ahead of where the video position is for me.
This seems to follow buffering, which is why I suspect it is a connection speed problem. I don't mind delay in the video, I lower the quality for a bit and it's fine, but while the video buffered the chat keeps moving and then when it comes back the chat is stuck a few seconds ahead of the video, definitely not as long ahead as the time it took to buffer but still noticeably ahead because I'll find out about something that's about to happen a good 5 seconds before it actually happens on the stream.
This is only really a problem with streams like xQc where chat is moving at supersonic speed. It kinda spoils the experience a bit though, I don't know how complicated it would be to fix or if it's worth your time because most streams don't have such a fast chat, but if there is a way it would definitely improve the juicer experience.

**Comment by samfundev** [comment]
I believe this is caused by the stream delay that Twire has compared to watching Twitch on the desktop. Unfortunately, there's not too much we could do to fix this problem besides reducing the stream delay. Feel free to keep an eye on #94 for more information about getting the latency to match the desktop.
