### ISSUE TITLE
ads video before start play stream

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [twireapp/Twire#21]
twicht api modified , before stream ads appear for hp omen ,

**Comment by aidalgol** [comment]
I'm also getting preroll ads even on channels I'm subscribed to.

**Comment by Perflyst** [comment]
I guess this can be closed? Ads were removed with https://github.com/twireapp/Twire/commit/eaf098a259ace20c0c03e1ed2305790b5563ec63

**Comment by samfundev** [comment]
Yep, I'm going to close this issue. Ads are probably going to be something that keeps popping back up, so feel free to open another issue if ads start happening again.
