### ISSUE TITLE
Portrait Stream View is broken

### ISSUE THREAD

**Issue by Nickwasused** [twireapp/Twire#212]
The Portrait Stream view is broken since https://github.com/twireapp/Twire/commit/f0c85d16cf1865a8ce01d5b33edd3104d36f4ef2

The Problems:

- When watching a Stream in Portrait view the Stream Chat goes black. But when clicking on the Stream to for example access the Controls the Chat comes back.
- The Controls are Stuck to the Top (as seen in the second video).

The Problems can be seen in the second video.

Device Info:
- Android Virtual Pixel XL, Android 11.0
- Xiaomi Redmi Note 7, Android 11.0

Expected Behaviour:
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/rGs-u9TTz7Q/0.jpg)](https://www.youtube.com/watch?v=rGs-u9TTz7Q)

Current Behaviour (18.4.2021):
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/cY0MTLa6sT0/0.jpg)](https://www.youtube.com/watch?v=cY0MTLa6sT0)

Possible Fix:
change `implementation "androidx.constraintlayout:constraintlayout:2.0.4"` back to `implementation "androidx.constraintlayout:constraintlayout:1.1.3"`

**Comment by KandiPanda** [comment]
Encountering the same thing in the 2021-04-20 14:02(GMT) debug build, in both portrait and landscape orientations. Also makes the gear menu pretty much impossible to access, attempting to click it selects the "back" arrow that it overlaps with and goes back instead.

Happens when logged out, unknown if it happens or not when logged in (unable to log in with Twire on my phone).
Also unknown if it happens in any versions in-between the mentioned debug build and Release 2.519, as any release version after 2.519 up to and including latest (2.9.3) would crash when I attempted to skip login, and as mentioned, login doesn't seem to work on my phone yet.

Device Info: 
- Casio C811, Android 4.1.2

**Comment by KandiPanda** [comment]
Update, same build as above:

Opening a stream in landscape and then rotating the screen to portrait does allow chat to stay on screen when the controls aren't on screen. Controls are still in the (same) wrong place when displayed though, also chat doesn't use the full portrait screen width when using this approach to keeping it on-screen (see attached screenshot).

![Screenshot_2021-04-25-14-29-09](https://user-images.githubusercontent.com/43508599/116007014-4487ee00-a5fd-11eb-875f-9370c7dec050.png)

**Comment by KandiPanda** [comment]
Further discoveries related to the above. (Currently using the (timedatehere) debug build.)

When using the above trick to keep chat visible, in landscape diaplay, the controls appear to display in the correct places, but are still stuck to the top in portrait. **However**, if you then go into "chat only" using the options and then exit chat only, in portrait mode it will then shift the video and chat down to display the upper controls between the top of the screen and the video, and the lower controls between the video and chat. However the video and chat stay shifted when the controls aren't displayed, further reducing chat area. (See attached screenshots.)

![Screenshot_2021-05-03-20-39-50](https://user-images.githubusercontent.com/43508599/116952294-d5a03a00-ac79-11eb-9a9f-9a05edcc67e3.png)
![Screenshot_2021-05-03-20-39-55](https://user-images.githubusercontent.com/43508599/116952297-dafd8480-ac79-11eb-97a5-b4c55c12ebec.png)

**Comment by samfundev** [comment]
Using match_parent seemed to be tolerated (but not recommended) in the 1.X.X versions of the ConstraintLayout but breaks things in 2.X.X. I've replaced all of them with match_constraint/0dp.
