### ISSUE TITLE
Emoji Menu stays open and cannot be closed

### ISSUE THREAD

**Issue by MrTeeXD** [twireapp/Twire#213]
So, apparently, when you open the Emoji Menu and then try to click the Emoji Button again to close it, it will stay open until a stream has been closed and re-opened.

**Comment by samfundev** [comment]
While it isn't possible to get this to work 100% perfectly, I did rework this menu so that it hopefully happens less. And if it does happen, you should be able to press the back button to close it without closing the stream.
