### ISSUE TITLE
Never connecting to chat

### ISSUE THREAD

**Issue by xelrix** [twireapp/Twire#237]
Version: 2.9.3 from fdroid and github release
Android 11, custom rom (arrow os} poco x3 pro

App wouldn't connect to chat, ever, despite waits.
Would either shows connecting or reconnecting.

**Comment by Nickwasused** [comment]
Can you try again with the latest APK from here (https://github.com/twireapp/Twire/suites/3294745823/artifacts/76948670)?
There are two options now in Settings > Twitch Chat > Enable Secure Connection
Please try it when enabled/disabled.

**Comment by xelrix** [comment]
Yes! It is working with said setting enabled.
Both on wifi and mobile network, with and without vpn.

**Comment by Nickwasused** [comment]
The emote problem is going to be tracked in #245 
Thanks for testing!
