### ISSUE TITLE
No login screen

### ISSUE THREAD

**Issue by skmdab** [twireapp/Twire#244]
At least it doesn't shows login screen page..
What is this.!?

**Comment by Nickwasused** [comment]
1. Which Version are you using? (e.g 2.7.3)
2. Can you login using another device? (e.g. a Desktop PC)

**Comment by skmdab** [comment]
11

**Comment by peepopoggers** [comment]
?

**Comment by Nickwasused** [comment]
This seems to be the same issue as #242. Please follow the steps described over there.
