### ISSUE TITLE
Missing Twitch Standard Emotes

### ISSUE THREAD

**Issue by ein-bandit** [twireapp/Twire#245]
OS: Graphene OS / Android 11
Model: Pixel 4a
Twire v2.9.3

Standard Twitch Emotes missing (eg LUL). 
Also typing emote shortcodes in chat (eg LUL) does not translate to emote, just prints text. 
List of emotes is empty for standard Twitch emotes. 

Recently Used, Sub-Emotes and BTTV are working. 

Anything I can change in the app to make this work?

**Comment by ein-bandit** [comment]
Emotes are also missing on device 
OS: Android 11 / One UI 3.1
Model: Galaxy Tab A

**Comment by Nickwasused** [comment]
Seems related to this Log:
```
W/System.err: org.json.JSONException: No value for sets
W/System.err:     at org.json.JSONObject.get(JSONObject.java:400)
        at org.json.JSONObject.getJSONObject(JSONObject.java:620)
W/System.err:     at com.perflyst.twire.chat.ChatEmoteManager.loadCustomEmotes(ChatEmoteManager.java:113)
W/System.err:     at com.perflyst.twire.chat.ChatManager.doInBackground(ChatManager.java:139)
        at com.perflyst.twire.chat.ChatManager.doInBackground(ChatManager.java:43)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

**Comment by Nickwasused** [comment]
Emote Url when joining Channel:
`https://api.twitch.tv/kraken/users/144225231/emotes?oauth_token=********************`

Response:
`{"error":"Gone","status":410,"message":"v3 is a lie but v5 is still alive. See https://dev.twitch.tv/docs"}`

@ein-bandit You can change nothing in the App to fix it. It's an issue by Twire.

**Comment by Nickwasused** [comment]
Fixing this seems not that easy:

This was used before:
https://dev.twitch.tv/docs/v5/reference/users#get-user-emotes

But because of #236 this has been removed.
In the new Api there is no endpoint for that:
https://dev.twitch.tv/docs/api/migration
![firefox_ykJKlaJNcB](https://user-images.githubusercontent.com/34883496/135141770-7b4c2ab0-a1dc-48ee-aadf-e1b5ffa87365.png)

**Comment by ein-bandit** [comment]
Just found this. Not sure if it helps though...
https://discuss.dev.twitch.tv/t/announcing-api-endpoints-for-twitch-emotes/32073

**Comment by Nickwasused** [comment]
Can you test again using this APK? (https://github.com/twireapp/Twire/suites/4006474713/artifacts/101115584)

`The APK is coming from here: https://github.com/twireapp/Twire/runs/3846552975`

**Comment by Foexle11** [comment]
Same Issue here btw.
Samsung Galaxy A70 with Andorid 11 - One UI 3.1
Twire is at Version 2.9.3 aswell.
Probably not helping much, but perhaps mentioning it helps somehow ._.
