### ISSUE TITLE
Any chance of a new version one day?

### ISSUE THREAD

**Issue by thinkpad4** [twireapp/Twire#255]
Hi, any chance of a new version adding in some of the newer ways of blocking ads that have appeared lately?

Thank you very much

**Comment by Nickwasused** [comment]
2.10.0 is Released. Please see: https://github.com/twireapp/Twire/releases/tag/v2.10.0

**Comment by Ammako** [comment]
2.10.0 still shows as 2.9.3 in the app info on my end, just me or?

It also fails to bring up the changelog, because of the version number remaining the same.

**Comment by samfundev** [comment]
@Ammako Sorry about that, I completely forgot to bump the version number. Should be fixed now.
