### ISSUE TITLE
Rotating phone while on login page resets intro screen

### ISSUE THREAD

**Issue by PMcca** [twireapp/Twire#263]
When on the Twitch login page, if the phone's orientation is rotated, the entire introduction sequence will reset to the beginning. 
May also be a good fix to lock screen orientation whilst not on video playback; the app doesn't seem to respect the user's configuration at this point.

**Comment by Nickwasused** [comment]
There is a fix for the login screen. It would be nice if you test it.
For the other problem please open another issue and describe your problem there with as much information that you can provide.

The Apk attached is up to date with 2.10.0 containing the patch. The app is built by Github actions as you can see here: https://github.com/twireapp/Twire/actions/runs/1487516860 and here: https://github.com/twireapp/Twire/pull/267 (click on "Show all checks")

The File:
[app.zip](https://github.com/twireapp/Twire/files/7576885/app.zip)
