### ISSUE TITLE
Stuck on the enter code after logging in with my info

### ISSUE THREAD

**Issue by Labib235** [twireapp/Twire#265]
Version 2.10.0 on Lineage OS 14.1 on Galaxy S Duos 2.Had the same issue on the previous version as well. Help
![16372989079646350724592381792439](https://user-images.githubusercontent.com/91120351/142569114-36263f34-2762-4154-9692-45da722f9a13.jpg)
Stuck on this screen for more than 5 minutes

**Comment by Nickwasused** [comment]
This seems to be the same issue as #242. Please follow the steps described over there.
