### ISSUE TITLE
2.10.0 not on F-Droid

### ISSUE THREAD

**Issue by yephny** [twireapp/Twire#268]
Why isn't the latest version of the app on F-Droid yet?

**Comment by jotoho** [comment]
Perhaps a new entry has to be added to https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.perflyst.twire.yml for them to build the new version?

**Comment by jotoho** [comment]
I don't see 2.10.0 listed there

**Comment by jotoho** [comment]
Reported it to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/issues/2544

**Comment by Perflyst** [comment]
Thanks for reporting to f-droid. It looks like their build servers didn't catch it at all, there is no (failed) build log at https://f-droid.org/repo/com.perflyst.twire_524.log.gz

**Comment by Perflyst** [comment]
According to https://github.com/twireapp/Twire/issues/255#issuecomment-968402032 it looks like @samfundev tagged 2.10.0 before bumping the version and then force-pushed to master? :o 

We can now either push 2.10.1 or re-tag 2.10.0 on f17e954b227b3f66c8f4747bb4e7fa9d5b68267a

**Comment by Perflyst** [comment]
I re-tagged 2.10.0, see https://github.com/twireapp/Twire/releases/tag/v2.10.0
F-Droid should catch up in a few days, I guess you can close the issue @jotoho on fdroiddata.

**Comment by jotoho** [comment]
@Perflyst 

> F-Droid should catch up in a few days, I guess you can close the issue @jotoho on fdroiddata.

Issue has been closed.

**Comment by KaKi87** [comment]
Hello, version `2.10.0.254` is available from Aurora Droid on my Android smartphone but not on my Android media player, so I had to manually download the APK for that device.

Thanks

**Comment by Perflyst** [comment]
Is your index up to date? The latest version is available as you can see on https://f-droid.org/en/packages/com.perflyst.twire/

 Version 2.10.1 (525) - Added on 2022-01-23 
 Version 2.10.0 (524) - Added on 2021-12-07

**Comment by KaKi87** [comment]
Oh, I thought that was automatically refreshed when using search, I guess not. Thanks
