### ISSUE TITLE
Can't play livestreams of followed streamers

### ISSUE THREAD

**Issue by el-o-l** [twireapp/Twire#273]
When signed into an account, followed streamers can't be viewed live. When clicking on their livestream it takes you to the previous page, even if you manually search up their stream. If the followed streams page is the landing page after opening the app, doing so closes the app.

**Comment by ein-bandit** [comment]
same issue. allthough on pixel 4a Android 12 clicking on a stream the screen turns fully white and game over

**Comment by ein-bandit** [comment]
i downgraded to 2.9.3, then upgraded back to 2.10.0 and the problem disappeared.
i lost all of my settings though

**Comment by ein-bandit** [comment]
@el-o-l you may reset the app on your phone to test if the issue resolves then.
Settings - Apps - Twire - Clear Storage
Your app will be reset to default (lose all settings) and you will have to login again

**Comment by Para-lyzed** [comment]
I can confirm that I had this issue on updating to 2.10.0. Clearing the storage fixed the issue for me as well.

**Comment by el-o-l** [comment]
> @el-o-l you may reset the app on your phone to test if the issue resolves then. on Android navigate to Settings - Apps - Twire - Clear Storage Your app will be reset to default (lose all settings) and you will have to login again.

Yep, that sorted it. Appreciate you!

**Comment by ein-bandit** [comment]
this issue occurred again on my pixel 4a Android 12.
again, resetting the app (clear storage) made livestreams work
