### ISSUE TITLE
App starts in landscape orientation

### ISSUE THREAD

**Issue by ein-bandit** [twireapp/Twire#274]
After installing new version 2.10.0, the app started in fixed landscape orientation and i had to redo twitch login. 
The new version is not respecting current orientation of phone when opened for the first time.
This behaviour was also inherited to the integrated login webview, so first app screen and web login screen was in forced landscape orientation. 
This was not an issue in previous version 2.9.3

Pixel 4a
Android 12
(I had "Auto-Rotate" disabled and used fixed Portrait mode, but i do not think this issue is settings related)

**Comment by ein-bandit** [comment]
i think this is fixed. did not occur again. shall we close this issue?

**Comment by samfundev** [comment]
Sure, closing since it's fixed.
