### ISSUE TITLE
Add 7tv emote integration

### ISSUE THREAD

**Issue by Para-lyzed** [twireapp/Twire#278]
Hello,

There's a new Twitch emote extension on the block like FFZ and BTTV. It's called 7tv and it's been gaining a lot of popularity recently, so it may be worth adding support for it when there is time to do so.

**Comment by Nickwasused** [comment]
It's getting worked on, please see #232 for that.

**Comment by Para-lyzed** [comment]
Awesome! I should've checked the pull requests before posting an issue, I just didn't see any other open issues about it.
