### ISSUE TITLE
cannot build on local machine

### ISSUE THREAD

**Issue by ein-bandit** [twireapp/Twire#281]
build fails

which jdk do i need to use?

jdk 17 did not work, tried upgrading gradle, did not help

**Comment by samfundev** [comment]
Sorry, you should use JDK 11. I've updated the project files which should fix this. Let me know if you're still running into issues.

**Comment by ein-bandit** [comment]
no worries. i'll give jdk 11 a try. 
still i want to suggest to state necessary dev setup and sdk versions in Readme or another document

**Comment by ein-bandit** [comment]
works. needed to delete debug.keystore so it can be regenerated, but works now :)

**Comment by samfundev** [comment]
I've added a [contributing](https://github.com/twireapp/Twire/blob/master/.github/CONTRIBUTING.md) file which includes this information.
