### ISSUE TITLE
Can't See Chat when Watching Vods?

### ISSUE THREAD

**Issue by jupiter-august** [twireapp/Twire#298]
When I open a vod, the app does not show me a chat replay anywhere. Is this a bug, me missing something somehow, or is it simply a missing feature?

If it's a missing feature, I highly suggest it! It's fun to look at chat replay. Or perhaps I want to find a link that I was shown or something important someone told me at a certain point in the VOD.
Without chat replay, I can't find said things.

So, I'd highly suggest adding chat replay when watching VODs! Thanks :)

**Comment by samfundev** [comment]
Do you see this arrow when opening up a VOD? If you click on that or swipe from the right side of the screen, it should open the chat replay.
![image](https://user-images.githubusercontent.com/6759716/150184292-8e5a672e-14bd-4cc8-94be-0201d470e989.png)
