### ISSUE TITLE
The 7TV Emotes setting doesn't work

### ISSUE THREAD

**Issue by AitoZ** [twireapp/Twire#299]
As the title says, the option to toggle the setting doesn't work.

**Comment by eocow** [comment]
Same problem here too.

**Comment by Nickwasused** [comment]
Fixed by #315

**Comment by quepperson** [comment]
it still doesnt work for me

**Comment by Nickwasused** [comment]
There was no release after the fix, so you need to wait for 2.10.3

**Comment by quepperson** [comment]
got it, thank you
