### ISSUE TITLE
Cannot navigate on Android TV

### ISSUE THREAD

**Issue by ClementNerma** [twireapp/Twire#304]
Hi there!

On the last versions of the app (included the latest release 2.10.1 downloaded from GitHub) I cannot navigate using Android TV.

For instance, I cannot select the fields of the login form, meaning I can't login in the app.

And while I can navigate with the "arrow" keys on my remote to open the app's menu, I cannot select any item in it. The Up/Down keys will only navigate the streams list even when the menu is open.

This didn't happen when I originally used the app nine months ago.

Is there any way to avoid this problem?

Thanks in advance for your help.

**Comment by AitoZ** [comment]
On Android TV use [S0undTV - GitHub (Standalone)](https://github.com/S0und/S0undTV/releases/latest) | [S0undTV - Google Play](https://play.google.com/store/apps/details?id=com.s0und.s0undtv) instead, just my two cents.

**Comment by ClementNerma** [comment]
> On Android TV use [S0undTV - GitHub (Standalone)](https://github.com/S0und/S0undTV/releases/latest) | [S0undTV - Google Play](https://play.google.com/store/apps/details?id=com.s0und.s0undtv) instead, just my two cents.

Works perfectly fine, thanks!
