### ISSUE TITLE
Twitch servers not loading or dont react

### ISSUE THREAD

**Issue by barnam2116** [twireapp/Twire#307]
Since today afternoon the twitch servers are not loading. The app says twitch servers not loading or not responding. Does anyone have the same issue? 
![Screenshot_20220209-212340_Twire](https://user-images.githubusercontent.com/92015677/153283987-a25a13fa-8d5b-437c-b409-70d341531485.jpg)

**Comment by Natnie** [comment]
I just downloaded Twire for the first time and immediately encountered this :(

**Comment by barnam2116** [comment]
I love twire so I hope the devs can fix it

**Comment by barnam2116** [comment]
I love twire so I hope the devs can fix it

**Comment by Donkey-Doug** [comment]
Same

**Comment by Natnie** [comment]
When I try to log in I get this message
![Screenshot_2022-02-10-07-44-40-53_adcdab2c001f286530e320a1fbca5cad](https://user-images.githubusercontent.com/17808005/153287140-1af51c21-e0e5-4693-b8fd-04f9e7f1020f.jpg)
:

**Comment by Nickwasused** [comment]
I think your error is related to the Shutdown of the Twitch Kraken API. (#236)

Here is the time schedule:

- February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
- February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
- February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
- February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
- February 21, 2022 – 24-hour shutdown starting at 11:00am PDT
- February 28, 2022 – v5 permanent shutdown
