### ISSUE TITLE
Crash on the latest version

### ISSUE THREAD

**Issue by AitoZ** [twireapp/Twire#313]
After selecting a game in the Top games category the app crashes and the app can't be used without an account as far as I've seen.

I've tested a bit further, if I search for example Apex Legends it gets recognized in the Streams/Streamers tab but not in the Games tab. The crash also happens when you select a game in the Search category, something is clearly wrong when it fetches the game information.

The appearance isn't saved if you change the system language, the theme for example.

**Comment by samfundev** [comment]
@Nickwasused It seems like it's [this line](https://github.com/twireapp/Twire/blob/master/app/src/main/java/com/perflyst/twire/model/Game.java#L59). I think you changed this code so I'm not sure what the correct index is.

**Comment by Nickwasused** [comment]
A fix is being implemented in #320
