### ISSUE TITLE
Stuck after logging in 

### ISSUE THREAD

**Issue by unicyclesarecute** [twireapp/Twire#316]
Unsure if I should post in the pinned thread, but I'm having the same issue even after entering the verification code.

A blank webpage with

The webpage at http://localhost/oauth_authorizing#access_token=5lyilo2h05u8aexoeshdcrhg0riwmh&scope=user_read+chat%3Aread+chat%3Aedit+user_follows_edit+user_subscriptions&token_type=bearer could not be loaded because:

net::ERR_CONNECTION_REFUSED

pops up and I am unable to continue. Without logging in, no streams show up and the twitch servers not responding message shows up.

I am using the latest version, 2.10.1, and am on Android 12, no custom ROM. I have been able to log in on a browser using the same phone and with a computer.

**Comment by saasasasasa** [comment]
Try the newer version 2.10.2, https://github.com/twireapp/Twire/releases/tag/v2.10.2

**Comment by unicyclesarecute** [comment]
Thank you! Was using FDroid and didn't see that version.
