### ISSUE TITLE
cant log in since yesterday

### ISSUE THREAD

**Issue by hyp0001** [twireapp/Twire#317]
not able to log in since yesterday, had a message saying "twitch servers seem to not be responding", tried logging out, now cant log in

**Comment by nicemanman** [comment]
I have this problem too, same error message

**Comment by Blipbliptoryah** [comment]
Webpage not available
The webpage at http://localhost/oauth_authorizing#access_token=ugkx0jzlpq50nwbqebg3x3xs18r3e4&scope=user_read+chat%3Aread+chat%3Aedit+user_follows_edit+user_subscriptions&token_type=bearer could not be loaded because:

net::ERR_CONNECTION_REFUSED

**Comment by nicemanman** [comment]
Well, this Is weird. I have an active account in app. Something with twitch api?

**Comment by nicemanman** [comment]
2.10.2 works fine. Thank you.

**Comment by hyp0001** [comment]
2.10.2 works, thank you
