### ISSUE TITLE
Can't search for games

### ISSUE THREAD

**Issue by Xyan1337** [twireapp/Twire#321]
When i go to "top games" or search for games and then click on any game it puts me back to the "my streams" page.

**Comment by AitoZ** [comment]
Should be fixed with the last commit, wait for the next update.

**Comment by Nickwasused** [comment]
Please test again when 2.10.3 is released.

**Comment by thinkpad4** [comment]
@AitoZ any idea when 2.10.3 will be released?  I would like to search for games again.  Thank you very much

**Comment by AitoZ** [comment]
@thinkpad4 When @samfundev has some time to update the app, I've nothing to do with the app I'm just a user like you.

**Comment by thinkpad4** [comment]
Oh, sorry for tagging you

**Comment by samfundev** [comment]
Version 2.10.3 has been released!
