### ISSUE TITLE
Chat show connection failed in replay 

### ISSUE THREAD

**Issue by leo0215** [twireapp/Twire#326]
So after install new version of Twire,no matter enable or disable Chat ssl connection,It always show Connection failed or Connection problem ,but it work on streaming video
![Screenshot_2022-03-02-01-40-30-94_adcdab2c001f286530e320a1fbca5cad](https://user-images.githubusercontent.com/37405572/156220443-a56f6348-848f-4d8a-aa87-a7d9e3a54fba.jpg)

**Comment by catska2jc** [comment]
I have this issue as well, any fix?

**Comment by samfundev** [comment]
I believe this has been fixed by 8dd41a4. If this is still broken on [this build](https://github.com/twireapp/Twire/suites/7289309922/artifacts/293868028), please let me know.
