### ISSUE TITLE
Steam and chat are delayed

### ISSUE THREAD

**Issue by itneveroccurred** [twireapp/Twire#344]
I dunno if it's just me or the streamer I watch (xQcOW), but chat is delayed by a whole 10-15 seconds which I noticed whenever I saw people mention things that showed up a bit later. Not sure if it's been mentioned yet or if there's a work around, but it bothers me because it always feels like a constant spoiler instead of just being there in the moment lol.

**Comment by samfundev** [comment]
This is a duplicate of #94 and should be resolved by #340.
