### ISSUE TITLE
Video size enlarged and distorted when returning to app

### ISSUE THREAD

**Issue by theridon** [twireapp/Twire#350]
Normally:

![normal](https://user-images.githubusercontent.com/85383195/176092504-41b78ae4-f933-4bef-a163-ff1a7cf653d9.jpg)

If I exit the app, and return to it later, the video becomes stretched over the screen like this

![notnormal](https://user-images.githubusercontent.com/85383195/176092517-6c45ba55-e4ec-4a42-804b-1dc24956cf8f.jpg)

I disabled mini player through my android because I don't like the streams continuing to play after I exit the app, I wonder if that has anything to do with it?

Would appreciate a fix. It's very very annoying...otherwise a phenomenal app!

**Comment by Nickwasused** [comment]
I think this is the same as/or related to https://github.com/twireapp/Twire/issues/241
