### ISSUE TITLE
Extremely frequent failure to connect to chat during live streams

### ISSUE THREAD

**Issue by theridon** [twireapp/Twire#353]
About 30% of the time, and, when using the Debug App (which is necessary to fix the screen size when returning to app glitch) about 80% of the time, the app fails to connect to chat. A feature that makes it very frustrating to use an otherwise fantastic app. Anyone else have this problem?

**Comment by samfundev** [comment]
Which build are you using? I did fix a problem where the chat could get stuck in 83ba6e7879b1cd71b1a0f10e0636a1249d310c49. A build of that commit is available [here](https://github.com/twireapp/Twire/suites/7156689143/artifacts/284863789).

**Comment by ein-bandit** [comment]
I am having the same issue.

Chat is stuck in 'Connecting to chat...' mode and never finishes (never changes to "ready to chat") 

Can be fixed by closing and reopening the stream. 
Most probably this only tries to connect again, but solves the issue about every time.

**Comment by theridon** [comment]
I was using 2.10.2. It is now fixed using the download link you provided, 2.10.2-DEBUG! Thank you!
