### ISSUE TITLE
[Request] Be able to set "My streams" as the default page

### ISSUE THREAD

**Issue by Darkempire78** [twireapp/Twire#355]
Can you add a way to set "my streams" page as the default page ?

**Comment by Nickwasused** [comment]
You can set "My Streams" as default in Settings -> General -> Startup Page.

**Comment by Darkempire78** [comment]
@Nickwasused Twire is in French for me, but I cannot choose "My streams" ("Mes streams" in French) 
![Screenshot_20220716-112508](https://user-images.githubusercontent.com/50015928/179349097-36092b91-3ddb-401d-9395-df58c1211f21.png)

This this the menu (to compare the names of the pages) :
![Screenshot_20220716-112518](https://user-images.githubusercontent.com/50015928/179349112-e3817036-d549-484f-ac23-10881b526795.png)

**Comment by zeropi2021** [comment]
Twire 2.10.2
Android 7
Twitch logged in

![hOOhreB](https://user-images.githubusercontent.com/79403844/179405430-5fe5c14a-3561-4487-a6e3-3f3b16f26a5d.jpg)

**Comment by Darkempire78** [comment]
@zeropi2021 I'm not logged in

**Comment by zeropi2021** [comment]
@Darkempire78

Can you log in for a test? Maybe it affects these options in some strange way?

If the situation is still the same after logging into your account, the problem may be with Android 12 / Twire.

You can also check out the latest version 2.10.3, the log says that the translations have been improved in general and the French language seems to be 98%.
But for me on 2.10.2 as you can see the French language works fine with these options, but maybe it's the effect of Android 7... hard to say.

Apply the problem elimination method:
1 Log in to your account
2 Install 2.10.3
3 Check 2.10.1
If the problem persists, only devs can do something about it. ;)

**Comment by jilv220** [comment]
This is probably due to a login problem. I had the same issue, and i fixed it by logging in again.

**Comment by Darkempire78** [comment]
I can confirm @jilv220  because the problem is fixed when I am logged
