### ISSUE TITLE
[Bug] Black screen when the stream is embeded

### ISSUE THREAD

**Issue by Darkempire78** [twireapp/Twire#356]
I have a black screen when I leave Twire to embed the stream (android 12) : 
![Screenshot_20220716-013614](https://user-images.githubusercontent.com/50015928/179324729-298ebeff-08b0-4c5c-abbc-892985b6d88a.png)

But if i resize it, the screen works :
![Screenshot_20220716-013633](https://user-images.githubusercontent.com/50015928/179324757-705afc1b-a66c-407b-847a-e064b84c80ba.png)

After that I can move, zoom or anything and it works well

**Comment by samfundev** [comment]
Are you using 2.10.3?

**Comment by Darkempire78** [comment]
I open this issue when I was using 2.10.2, but it seems to be fixed now @samfundev
