### ISSUE TITLE
[Bug] 2.10.3 crashes when trying to run VOD on Android 7

### ISSUE THREAD

**Issue by zeropi2021** [twireapp/Twire#358]
Hi

Strange problem... 2.10.3 crashes when trying to run VOD on Android 7 :/

On 2.10.2 it worked normally... only after watching VOD for a long time it crashed so I was ignoring it hoping 2.10.3 will fix it unfortunately it only got worse. ;) 2.10.1 by contrast, it was flawless on Android 7 in this regard.

However, 2.10.3 crashes immediately when you try to watch any vod. Reinstalling the app did not help.

Here the recording of what it looks like on the screen... the lack of any error messages just total crashes https://streamable.com/8wtvbk
For comparison, behavior 2.10.2 https://streamable.com/pwd58b

Any idea?

PS
I am using the apk from here https://github.com/twireapp/Twire/releases/download/v2.10.3/Twire-2.10.3.apk

**Comment by samfundev** [comment]
I believe this is the same issue reported in #361.
