### ISSUE TITLE
Doesn't show any channels or games - Android 12

### ISSUE THREAD

**Issue by geekofix** [twireapp/Twire#365]
For a few weeks now the options like top streams, top games just stay blank. I refresh, but it doesn't show any channels or games. I tried to delete the cache, but it didn't work. I reinstalled it first from F-Droid and later directly from Github and it still doesn't work. I already had this problem before the release of the new version for a couple of weeks.

Device: Samsung SM-A515F
Android 12

**Comment by zeropi2021** [comment]
@geekofix

Are you logged in? If not, log in to your account...

**Comment by samfundev** [comment]
Are you having this problem on 2.10.3?

**Comment by test2a** [comment]
not logged in. i installed latest apk from github and there is no top streams or top games

**Comment by geekofix** [comment]
1. The login didn't work for some time.
2. Without login there were no featured channels, no categories, which worked in the past.
3. Now the login worked and I see everything again.

**Comment by testman42** [comment]
I'm having this issue as well with 2.10.4 on LineageOS 19 (Android 12)

**Comment by samfundev** [comment]
As zeropi2021 mentioned, login is now required due to changes that Twitch has done. Unofficial APIs (like GraphQL) would need to be explored to get this information without logging in. Feel free to make a separate issue about trying to restore logged out functionality.
