### ISSUE TITLE
Question: Settings - Follows

### ISSUE THREAD

**Issue by ein-bandit** [twireapp/Twire#366]
What do these options do?
- Wipe all follows
- Import Follows

Import follows always shows me "Imported 0 Follows".
Should Wipe all follows clear all local follows?

Export Follows worked for me.

At first I was not brave enough to click the "wipe all follows" button. 
Maybe there should be information about this options somewhere, at least here on github, what it does and when to use.

GrapheneOS / Android 12
Pixel 4a

**Comment by zeropi2021** [comment]
Does what it says. ;)
It does the export and import of those channels which you track or clean completely.

The export is located in /your drive/Android/data/com.perflyst.twire/files/Documents/ export.json
At least that's the case in Android 7.0

You can do the export and copy the file export.json to a safe place and after clean twire installation you can copy this file again to that place and do the import. This can be useful when, for example, you reset the device and you don't want to painstakingly add channels to the twire...

**Comment by ein-bandit** [comment]
ok. so it does only refer to local/in-app follows.
i found the exportes file.
understood, thank you

**Comment by ein-bandit** [comment]
still i think new user may not be aware that the mentioned options are for in-app/local follows only.
and the options do not interfere with twitch account follows.
