### ISSUE TITLE
Show stream title while watching stream

### ISSUE THREAD

**Issue by ein-bandit** [twireapp/Twire#367]
In Settings Appearance I selected Stream Style "Expanded", which shows 'Stream Title' in the preview example.

When watching a stream I do not get the stream title displayed.

Maybe I just don't know how to activate/trigger the Stream Title bar.

GrapheneOS / Android 12 | Pixel 4a

**Comment by samfundev** [comment]
The stream style effects show the stream is shown when browsing, not when watching the stream. There is currently no way to show the title of the stream. I'm going to mark this as a feature request since I'm assuming that's a feature you would want.
