### ISSUE TITLE
App crashes on stream playback - Android 7.1.2

### ISSUE THREAD

**Issue by Staycalmsyndrome** [twireapp/Twire#370]
It crashes when i try to play any stream. This does not happen on 2.10.2.

 - Device: Galaxy Tab S2
 - Android Version: 7.1.2
 - Twire Version: 2.10.3

**Comment by samfundev** [comment]
Duplicate of #361, should be a new release soon.

**Comment by Staycalmsyndrome** [comment]
thank you.
