### ISSUE TITLE
The navigation bar is shown the entire time

### ISSUE THREAD

**Issue by AitoZ** [twireapp/Twire#371]
On the latest version (2.10.4) the player doesn't go into fullscreen, the navigation bar is shown the entire time. It doesn't matter if the option: "Reveal navigation bar on click" is on or off.

**Comment by zeropi2021** [comment]
Unfortunately, I see exactly the same behavior in 2.10.4, the full-screen / horizontal navigation bar does not disappear when playing video. Another video player has no problem with that, just like 2.10.2 did.

Android 7.0

**Comment by luke1337go** [comment]
Hi! I just upgraded from 2.10.2 to 2.10.4 and I have the same issue. The navigation bar and the horizontal notification bar don't disappear while in fullscreen mode/ holding the phone horizontally. It's like that with every in-app player for me.
Some phone information, let me know if you need more:
- Samsung SM-G960F
- Android 10, "One UI version 2.5"
- Kernel version: 4.9.118-23733677

Example video( MIGHT be a bit loud, be careful!): [https://streamable.com/td7mxl](https://streamable.com/td7mxl)
