### ISSUE TITLE
Ads/Commercial Break

### ISSUE THREAD

**Issue by Fireseed45** [twireapp/Twire#384]
Whenever a stream is opened a screen saying "Commercial Break in Progress" will appear for around 30 seconds. This also occurs during the stream as well.

**Comment by gilbsgilbs** [comment]
I found the following workaround: go to settings, "Stream player", and change "Stream player type" to "embed". Apparently, the player type is just an "internal" value that is sent to twitch's API. I'm not sure what it changes it practice, but doesn't seem to have any effect on the app itself (except for ads).

**Comment by derpyderpaderp** [comment]
> I found the following workaround: go to settings, "Stream player", and change "Stream player type" to "embed". Apparently, the player type is just an "internal" value that is sent to twitch's API. I'm not sure what it changes it practice, but doesn't seem to have any effect on the app itself (except for ads).

This method is no longer working. Getting ads no matter what I do for settings. Time for a much needed update.

**Comment by hahmetcakir** [comment]
Ads are displayed on the channels I subscribe to, even on my own channel, even though the ad display to subscribers is turned off.

**Comment by BedHedd** [comment]
I looked at the original fork and they seemed to have found a potential way to filter it
https://github.com/SebastianRask/Pocket-Plays-for-Twitch/issues/20

**Comment by samfundev** [comment]
Closing in favor of #403
