### ISSUE TITLE
Add 720p limit bypass feature [IMPORTANT]

### ISSUE THREAD

**Issue by RoonMoonlight** [twireapp/Twire#391]
**Is your feature request related to a problem? Please describe.**
Starting from September 30 2022, Twitch will force to 720p as maximum resolution in Korea, which led to controversy. Other countries are not affected for this change.

https://www.reddit.com/r/LivestreamFail/comments/xqwzr1/twitch_korea_is_forcing_their_viewers_from_sep/

**Describe the solution you'd like**
We need the method to bypass this limit so we all can watch maximum resolution like other countries.

**Describe alternatives you've considered**
Nothing.

**Additional context**
None.

**Comment by RoonMoonlight** [comment]
I hope this can be implemented with high priority, because 720p limit will take effect on Sep 30, 2022

**Comment by samfundev** [comment]
If there's a known way to bypass this, then we could implement it. I suspect the only way around this would be with a VPN, which I don't think would require any changes to be implemented into Twire.

Tagging as "needs more information" until it's known how to bypass this.

**Comment by RoonMoonlight** [comment]
> If there's a known way to bypass this, then we could implement it. I suspect the only way around this would be with a VPN, which I don't think would require any changes to be implemented into Twire.
> 
> Tagging as "needs more information" until it's known how to bypass this.

I just noticed TTV LOL can bypass the 720p limit, will you consider adding it?

**Comment by samfundev** [comment]
> I just noticed TTV LOL can bypass the 720p limit, will you consider adding it?

@Nickwasused opened #217 which would add it. I am not sure if they are still working on it.

**Comment by samfundev** [comment]
Closing now that #403 is closed.
