### ISSUE TITLE
Ads/commercial break screen

### ISSUE THREAD

**Issue by mca82** [twireapp/Twire#403]
Ads are coming through.

**Comment by samfundev** [comment]
I'm working on adding support for proxies, which seem to be the only thing that reliable gets around this issue.

**Comment by Phoenix616** [comment]
Ads and their placeholder screens) don't seem to show anymore with the twitch-for-kodi addon (not just for subscribed channels, I made sure of that) and I'm pretty sure they are getting the video directly from twitch in Kodi itself, might be worth looking into why that happens. The only thing I do is block ad-domains on a network level via hostnames which seems to work in the official app as well. (but Twire will show the placeholder screen instead which the others don't show)
