### ISSUE TITLE
I get Twitch starting stream screen for every stream. 

### ISSUE THREAD

**Issue by tless1217** [twireapp/Twire#404]
![Screenshot_20221116-104602_Twire.jpg](https://user-images.githubusercontent.com/99771463/202241814-ce3f7b18-f203-4dd3-99bb-c85593306cf7.jpg)[]()![Screenshot_20221116-104554_Twire.jpg](https://user-images.githubusercontent.com/99771463/202241852-a997222a-f962-4b06-857e-853e12d7101a.jpg)

**Comment by theridon** [comment]
I'm getting this too unfortunately. Twire use to play flawlessly with no ads.

**Comment by hornyjailfish** [comment]
same

**Comment by TBO1981** [comment]
For those that don't know twitch changed some things a week or so ago and all the adblock things for twitch have been having these problems, even pc browsers, the good news is those are starting to come around, I would assume its being worked on here and they are well aware. I do not speak for twire or anyone involved, I just know this is whats been going on.

**Comment by Fireseed45** [comment]
> For those that don't know twitch changed some things a week or so ago and all the adblock things for twitch have been having these problems, even pc browsers, the good news is those are starting to come around, I would assume its being worked on here and they are well aware. I do not speak for twire or anyone involved, I just know this is whats been going on.

do you know any workarounds for browsers?

**Comment by samfundev** [comment]
Closing in favor of #403
