### ISSUE TITLE
luminous-ttv support.

### ISSUE THREAD

**Issue by Sokoloft** [twireapp/Twire#406]
**Is your feature request related to a problem? Please describe.**
Ads play disrupting the live stream. Proxying the m3u8 request to a country that doesn't serve ads stops them from playing. luminous-ttv does this.

**Describe the solution you'd like**
Support for luminous-ttv. A setting in the options to add the server URL that is running on your local network or possibly even a vps.

**Describe alternatives you've considered**
As far as I know, there are none. I've tried using the official twitch app on my Amazon based tablet and it just crashes.

**Additional context**
[luminous-ttv server](https://github.com/AlyoshaVasilieva/luminous-ttv)
[luminous-ttv extension](https://github.com/AlyoshaVasilieva/luminous-ttv-ext)

Thanks.

**Comment by samfundev** [comment]
Related to #217

**Comment by Sokoloft** [comment]
I was unable to successfully use the try-ttv.lol branch that added video proxy support. I assume its using twitchs old API that is discontinued. The app gives an oops can't find twitch servers error at the bottom of the app. 

I really hope video proxy support is added to the master soon. However it seems development has stalled on that front.

**Comment by samfundev** [comment]
Closing in favor of #403
