### ISSUE TITLE
App Freezes When Playing VODs

### ISSUE THREAD

**Issue by ScalableCodex** [twireapp/Twire#408]
**Describe the bug**
When playing a VOD, the app freezes, forcing me to "wait" or "close app"

**To Reproduce**
1. Open a VOD and it'll freeze. 

Android 11
A52 5G

Earlier today it worked, seems to have started the last few hours.

**Comment by zeropi2021** [comment]
Same situation for me.

Android 7

**Comment by el-o-l** [comment]
Android 11, same experience.

The video and audio itself does play but the app can't be interacted with otherwise and the time stamp for the video is frozen.

**Comment by t0pu** [comment]
It seems that Twitch shutdown their v5 video comments API. I'm surprised it kept working after 2022-02-28, which was the official deprecation date for v5. The endpoint now only returns `410 Gone`. This error is not properly handled, so the UI freezes up.

**Comment by lamdacore** [comment]
> It seems that Twitch shutdown their v5 video comments API. I'm surprised it kept working after 2022-02-28, which was the official deprecation date for v5. The endpoint now only returns `410 Gone`. This error is not properly handled, so the UI freezes up.

I managed to stop the freeze at least. The problem is that by reconnecting to chat the vodLock.wait() is never called again. but this is neccessary to have everything work. The chat tries to reconnect and sleep 2500 ms after every try. This is also not good that the after such a loong time the vodLock.wait() is not called anymore. So i make sure that this method is called after 100ms. now its working again .

im not familiar with github .. is there a possibility to share my code changes? how can i do that? Or is this only possible by selected member persons?

**Comment by xbello** [comment]
> im not familiar with github .. is there a possibility to share my code changes? how can i do that? Or is this only possible by selected member persons?

The easiest path is to fork **this** repo (the original) going to https://github.com/twireapp/Twire/fork, that should go into your account. Then clone your newly forked repo into your computer, make the changes in your PC, push to your repo, and from your Github repo create a pull request.

**Comment by t0pu** [comment]
@lamdacore There is a step by step guide by GitHub: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

I think a maintainer should decide if a hotfix version with the VOD chat disabled should be released, to make the VODs usable again or if a proper fix should be implemented before a new version is released.

Thoughts @samfundev ?

**Comment by zeropi2021** [comment]
It seems that one potential workaround solution could be blocking traffic to api.twitch.tv at the right moment.

I did some short tests (too short to be 100% sure) When we run Twire I allow traffic to "api.twitch.tv" we go to the channel, select vod, and open vod and immediately go to the firewall and block "api.twitch.tv" the effect is to eliminate twire hangs.

It has to be done very quickly. if we don't unblock "api.twitch.tv" at first then we won't be able to start vod, so blocking must happen a second after vod starts playing.

I don't use chat/comments and leave sessions logged in all the time...

If someone can confirm on their device whether the situation can be reproduced, I recommend using "NetGuard" or "NoRoot Firewall".

**Comment by t0pu** [comment]
For anyone who can't wait for a release. I've created a build with the VOD chat disabled.

https://github.com/t0pu/Twire/releases/download/v2.10.4-vod-chat-disabled/app-release-unsigned.apk

**No Warranty! Use at your own risk!**

_Please note that you have to uninstall the official version (from F-Droid etc.) of the app first, as my build is unsigned and can't be installed over the official one.
Uninstalling will make you loose your login,settings and local follows of course.
There is no backup/restore function to keep the settings._

**Comment by njmdietrich** [comment]
> For anyone who can't wait for a release. I've created a build with the VOD chat disabled.
That is very kind of you. Unfortunately, I can't install the apk, as it says "App not installed as package appears to be invalid". I did uninstall the official twire app before attempting to install this build.

**Comment by t0pu** [comment]
> > For anyone who can't wait for a release. I've created a build with the VOD chat disabled.
> 
> That is very kind of you. Unfortunately, I can't install the apk, as it says "App not installed as package appears to be invalid". I did uninstall the official twire app before attempting to install this build.

Try this new link: https://github.com/t0pu/Twire/releases/download/v2.10.4-vod-chat-disabled/app-debug.apk
