### ISSUE TITLE
App Doesn't Launch on Android 4.2.2

### ISSUE THREAD

**Issue by TheMercenary333** [twireapp/Twire#420]
**Describe the bug**
When I launch the app, I get the warning "Unfortunately, Twire has been stopped". In short, the app cannot be launched. 

**Smartphone (please complete the following information):**
 - Device: General Mobile E-Tab 4
 - Android Version: 4.2.2
 - Twire Version: 2.10.5

**Comment by mystixa** [comment]
I also get this. Android 4.4.4 cyanogen Twire 2.10.5 
tried going back to 2.10.4 but getting white screen login bug thats reported elsewhere.

**Comment by samfundev** [comment]
I'm going to close this since the minimum Android version is 5.
