### ISSUE TITLE
[Bug] "Preparing your stream" interstitial video

### ISSUE THREAD

**Issue by KaKi87** [twireapp/Twire#421]
**Describe the bug**
Everytime I open a stream, a video is displayed, forcing me to wait several seconds before being able to view the stream itself.

**To Reproduce**
1. Open a stream
2. Notice the video

**Expected behavior**
The actual stream is displayed immediately.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 8
 - Android Version: 13
 - Twire Version: 20.10.5

**Additional context / screenshots**
![](https://i.goopics.net/jl7j2s.jpg)

---
Thanks

**Comment by ShadowStorm0** [comment]
I'm getting this error too. The stream does start after a few seconds.

**Comment by KaKi87** [comment]
It's been a while so I switched to [Xtra](https://github.com/crackededed/Xtra) which doesn't have this issue and does have background playback.

**Comment by sh0wst0pper** [comment]
Unfortunately, even after the update, I get the same issue.

**Comment by samfundev** [comment]
Closing in favor of #403
