### ISSUE TITLE
The VOD stopped playing

### ISSUE THREAD

**Issue by zeropi2021** [twireapp/Twire#422]
Hi

In the last 24 hours twire 2.10.5 stopped playing any VOD... You can go to the channel and you can see the thumbnails of the vod, you can click on the vod, the vod starts but doesn't play, it stays on the thumbnail and doesn't play for a second.

What happened?

![tw](https://user-images.githubusercontent.com/79403844/232752956-718ace75-5292-48a1-b779-5c2e20cf6cc2.jpg)

**Comment by theridon** [comment]
> Same here but in addition live streams also do not play

Same. Looks like this app is dead.

**Comment by zeropi2021** [comment]
@samfundev Any news on the situation?

**Comment by QuestioningEspecialy** [comment]
Copying my comment from the above mentioned issue below...

This problem persists for both VODs and live streams.
> Failed to play VOD. Try another quality.
> Failed to play stream. Try another quality.

Started _maybe_ a month ago? Was originally a dice roll with whether or not it was gonna with a specific VOD/stream, and once it does it's consistent. Today, it seems to consistently happen even after a phone restart. The live chat seems to work fine, but I haven't bothered saying anything to fully test it.

**Smartphone:**
 - Device: Google Pixel 6a
 - Android Version: Android 13
 - OS: GrapheneOS
 - Twire Version: 2.10.5

**Comment by astormf** [comment]
Same

**Comment by astormf** [comment]
Same

**Comment by astormf** [comment]
Same

**Comment by zeropi2021** [comment]
If someone needs an application for "now" then the "Xtra" app looks encouraging, available, among others, on F-Droid.

https://f-droid.org/packages/com.github.andreyasadchy.xtra/

**Comment by ckeller** [comment]
Same on:
- Fairphone 3
- Android 11
- Twire 2.10.5
Thanks for the nice app by the way!

**Comment by samfundev** [comment]
Apologizes, I should have gotten a release out sooner. Check out 2.10.6, which is out now!
