### ISSUE TITLE
Vod Chat only displays one page of messages and then stops

### ISSUE THREAD

**Issue by midahp** [twireapp/Twire#424]
**Describe the bug**
When watching a vod with chat the first ~50 messages get displayed but then it just stops.
When seeking the vod to a different position it will again show some chat messages and then stop again.

**Steps To Reproduce**
- Open a Vod of a channel
- Click the fullscreen button to show the chat
- Wait a few seconds - no more messages a appearing. This is easiest to see for very active chats (because then it stops immediately) but also happens for slow chats.

**Smartphone:**
 - Device: Samsung Galaxy A53 5G
 - Android Version: Android 13
 - Twire Version: 2.10.6

**Comment by Shiroy0** [comment]
same
