### ISSUE TITLE
Streams randomly closing in the middle of watching

### ISSUE THREAD

**Issue by Rocker26a** [twireapp/Twire#425]
Every time I open a stream, after a couple of minutes, it'll just close and go back to my startup page.

It happens on all of my devices, but in particular my Fairphone 3 running Android 11. My Twire app is version 2.10.7. Installed via F-Droid.

**Comment by LizardWithHat** [comment]
I got the same symptoms, just without the app automatically reopening to the startup page. Android 7 on a Google/Asus Nexus 7 2013.
I attached a logcat of three different crashes I quickly got logged. Looks to me like the app runs into a NullPointerException trying to get a badge name. This is also the F-Droid version.

[crash.log](https://github.com/twireapp/Twire/files/11778890/crash.log)

**Comment by LoneFenris** [comment]
I noticed this started for me a couple weeks ago I think. Here's my stacktrace.

[twirestack.log](https://github.com/twireapp/Twire/files/11779830/twirestack.log)

**Comment by IronGibbet** [comment]
After the last update published on F-Dorid I experience the same problem. Though I maybe get just past the initial commercials at the start of a stream sometimes not even that.

OS: Android 12 MIUI 13
Model: XiaoMi veux (EU rom) 
On WiFi: yes
On mobile data: yes 
logcat is rather large need to find the right entries.

**Comment by YohannGutej** [comment]
Twitch have changed the "badge" API, resulting in issues when displaying FrankerFaceZ badges.

I'm not a contributor but here's a little commit of changes to fix the issue : <https://github.com/twireapp/Twire/compare/master...YohannGutej:Twire:fix-425>

**Comment by gaekwad** [comment]
> Twitch have changed the "badge" API, resulting in issues when displaying FrankerFaceZ badges.
> 
> I'm not a contributor but here's a little commit of changes to fix the issue : [master...YohannGutej:Twire:fix-425](https://github.com/twireapp/Twire/compare/master...YohannGutej:Twire:fix-425)
I haven't looked at their policy for this stuff, but maybe try submitting a pull request?
This is a pretty major bug, it seems crazy to me that it still hasn't been fixed. Is this app dead?

**Comment by samfundev** [comment]
Apologizes for taking so long to get around to this. I'll be putting out an new release tonight.

**Comment by Rocker26a** [comment]
> Apologizes for taking so long to get around to this. I'll be putting out an new release tonight.

No sweat! Thanks for getting round to it in general!
