### ISSUE TITLE
 2.10.8 simply do not start

### ISSUE THREAD

**Issue by p0k33m0n** [twireapp/Twire#428]
**Describe the bug**
 2.10.8 simply do not start

**To Reproduce**
 2.10.8 simply do not start

Cleaning cache do not fix problem.

**Expected behavior**
Previous version worked fine, except one crash when re-return to stream.

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-J616F
 - Android Version: Android 12
 - Twire Version:  2.10.8

**Comment by samfundev** [comment]
Sorry about that, seems like R8 was causing problems in release mode. I've republished 2.10.8, let me know if you're still experiencing this issue.

**Comment by p0k33m0n** [comment]
WOW! It was fast. It works. Additionally crash when re-return to stream is fixed in that version. Good work!
