### ISSUE TITLE
Follows list is empty

### ISSUE THREAD

**Issue by Kuurse** [twireapp/Twire#431]
**Describe the bug**
Upon logging into the app, the "My Streams" tab is empty even though some streamers I follow (on Twitch, not locally) are live.

**To Reproduce**
Install Twire
Log into my Twitch account
Go to My Streams
Refresh 

**Expected behavior**
I was expecting to see all the streamers I follow who are live.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco F3
 - Android Version: Android 13
 - Twire Version: 2.10.8

**Additional context / screenshots**
I have tried logging into 2 separate Twitch accounts, with 2 phones (Samsung s22), tried clearing app data and doing a clean install, and I tried revoking Twire's authorization on Twitch and re enabling it by logging back into Twire.

![Screenshot_2023-09-17-17-43-49-311_tv.twitch.android.app.jpg](https://github.com/twireapp/Twire/assets/32364456/df783daa-6c94-4dc4-996e-d7e592acc7f7)

![Screenshot_2023-09-17-17-43-35-233_com.perflyst.twire.jpg](https://github.com/twireapp/Twire/assets/32364456/bd054c89-3f55-4a8e-b6f7-8aeb809bddfb)

**Comment by Drizzt321** [comment]
I'm seeing the exact same thing, My Streams and Followed Streamers are both empty. Freshly downloaded and installed from F-Droid, v2.10.8, and freshly logged in. Tried force-quiting and opening it up again, nothing. 

Android 13, LineageOS

**Comment by yoshimo** [comment]
You could checkout https://github.com/crackededed/Xtra/ instead

**Comment by KaKi87** [comment]
Well, while I'm experiencing this empty list issue on Twire, I'm also experiencing a [crashing player](https://github.com/crackededed/Xtra/issues/317) issue on Xtra 😅
