### ISSUE TITLE
7TV Settings doesn't work again

### ISSUE THREAD

**Issue by t1mb3rw0lf** [twireapp/Twire#445]
Description: 
Enabling 7TV emotes doesn't do anything. They just appear as text in chat. Also emote select menu for 7TV isn't there (stream supports 7tv, checked on web version)

Already tried:
- Using 2.10.3 version
- Restarting 2.10.9 after enabling the setting
- Clearing cache/all data and re-enabling the setting

Smartphone:
 - Device: Xiaomi 13 Lite
 - Android Version: Android 12
 - Twire Version: 2.10.9

**Comment by Kronagh** [comment]
Please fix 7tv.
