### ISSUE TITLE
Twire still retains unfollowed streamers

### ISSUE THREAD

**Issue by ghost** [twireapp/Twire#447]
as the title says, Twire *still* retains streamers that you've unfollowed in the followed streams section, despite this bug being first reported _**three years ago**_, and several comments mentioning that it's still present. it would be really great if this frankly critical bug was finally addressed and fixed after so long.

**Comment by p0k33m0n** [comment]
100% agree. But honestly, the program looks abandoned, so I wouldn't count on any update.

**Comment by samfundev** [comment]
If a bug is effecting you, please upvote the original issue so that I can better prioritize things.
