### ISSUE TITLE
'Favorites' page

### ISSUE THREAD

**Issue by fefo-dev** [twireapp/Twire#53]
Thanks for the work, it's nice to have a no-browser option to use twitch without an account.

Dunno how deep you want to go on the 'no account' end, but could you add a local favorites/inscriptions page? It would be great since the kind of stuff that I'm looking for only show up in the default pages once per year at best.

Thanks.

**Comment by samfundev** [comment]
It's now possible to follow users without a Twitch account, which is what I think request was getting at.
