### ISSUE TITLE
Twire not starting with android 4.2

### ISSUE THREAD

**Issue by robotrono** [twireapp/Twire#64]
I get this in the last version, Im using Android 4.2:

https://i.imgur.com/GfXIWCO.jpg

**Comment by Perflyst** [comment]
Min sdk is 16, so `Jelly Bean 	4.1.x 	API level 16` it should work.
Can you provide logs from logcat, please?

**Comment by Perflyst** [comment]
Please check if this is fixed with 2.517, will be on F-Droid in a few days

**Comment by samfundev** [comment]
Closing this due to a lack of information.
