### ISSUE TITLE
Twire remember user even when logged out

### ISSUE THREAD

**Issue by Porkepix** [twireapp/Twire#7]
I could notice it through `adb logcat` for another issue: after log in one time on Twire, and then log out, it seems to remember user information for the ChatManager component as I could still see my nickname in the logs.

**Comment by Nickwasused** [comment]
I have tested this on 8555da1b25b6152f6208a34afb767f71df9846a1 and I am not able to reproduce the problem.

**Comment by samfundev** [comment]
Closing since this appears to be fixed.
