### ISSUE TITLE
video player does not work

### ISSUE THREAD

**Issue by weachean** [twireapp/Twire#72]
Android-Version: 5.1.1
Twire-Version: 1.9.9 (F-Droid)
https://upload.vaa.red/4ac29#64174db9508ebe33a536aafac2093477

**Comment by samfun123** [comment]
I'm not sure what happened to the link but I can't view it so I don't know what this issue was referring to. If you could explain what it was referring to, I could look into the issue.

**Comment by samfundev** [comment]
Closing issue due to lack of information.
