### ISSUE TITLE
Copy followed list / local follows

### ISSUE THREAD

**Issue by madmadman** [twireapp/Twire#81]
I've seen this done in other Twitch apps. TD was my favorite Twitch app before it completely died off and with that all you had to do was enter your Twitch username (no password) and you'd see your entire list of streams that you follow.

Give me that same functionality here because signing in keeps breaking, it's super finicky and I'm fed up with it. I don't care about chatting on my phone.

**Comment by roshavagarga** [comment]
@samfun123 Would it be theoretically possible to improve on this idea by just inputting a local database of some sort? What I'd be very up for is either having a device-only method of following streams or just having a way to add streams to favorites locally.

**Comment by samfun123** [comment]
We could allow users who aren't logged in to use the follow button to add onto their follow list if that's what you mean.

**Comment by roshavagarga** [comment]
@samfun123 Pretty much, if that would enable people to have a local 'followed' list without actually having to create or use a Twitch account :)

**Comment by moshpirit** [comment]
Can this be implemented by using RSS as NewPipe does?

**Comment by samfundev** [comment]
@moshpirit In the case of NewPipe, YouTube provides an RSS feed that has all the channels that you're subscribed to. As far as I know, there isn't something like that provided by Twitch.

**Comment by roshavagarga** [comment]
> 
> 
> @moshpirit In the case of NewPipe, YouTube provides an RSS feed that has all the channels that you're subscribed to. As far as I know, there isn't something like that provided by Twitch.

There are Twitch RSS stream generators [out there](https://twitchrss.appspot.com), though I'm not sure they can be used in the same manner.

**Comment by BrachystochroneSD** [comment]
This feature would greatly improve this app indeed!

The twitch api (helix) is capable to check connected streams from a list (user_login=<channel_1>&user_login=<channel_2>..."). "Just" need to create a list locally I guess.

**Comment by samfundev** [comment]
I believe this issue is closed by #240. It is now possible to follow a streamer locally without a Twitch account. Please let me know if this issue isn't resolved.
