### ISSUE TITLE
api modified (ads before stream)

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [twireapp/Twire#85]
now when try see stream , comercial break in progres appear before video need wait 15-30 second for display stream

**Comment by Whovian9369** [comment]
Getting this too via the F-Droid available Stable

**Comment by Santo-7** [comment]
same issue

**Comment by samfundev** [comment]
I can reproduce this issue now and I think I've found a fix for it. Keep in mind that Twitch is constantly fiddling around with these things so the fix might get broken again.
