### ISSUE TITLE
Twire keeps going back to the previous screen when selecting a new tab sometimes

### ISSUE THREAD

**Issue by WulftheNordicRanger** [twireapp/Twire#91]
Using the latest version from fdroid on android pie.

**Comment by samfun123** [comment]
Can you give a more specific example of how this happens? This also might have been fixed by commit fc80766cd9a86ed34e84dc5fa53812e759c0784d. Let me know if you're still experiencing this issue when version 2.516 comes out.

**Comment by samfundev** [comment]
Closing due to lack of information.
