### ISSUE TITLE
Background playback

### ISSUE THREAD

**Issue by TeardropOmen** [twireapp/Twire#99]
There should be an option to have the audio continue to play in the background when you turn off the screen of the device.

**Comment by JohnVeness** [comment]
It would also be good to have the audio continue when switching to another app, without needing the PiP.

**Comment by nbros** [comment]
As a workaround I noticed that that you can click "Use external player" from the upper right hamburger menu in Twire in order to start playing in VLC for example which does support background playback!

**Comment by DeadNews** [comment]
[Firefox for Android](https://github.com/mozilla-mobile/fenix) also supports background playback.

**Comment by DeadNews** [comment]
[Xtra for Twitch](https://github.com/crackededed/Xtra) also supports background playback.

**Comment by israelfaustino** [comment]
Even though Xtra and other external players already have background playback, Twire is the only twitch app I know that has the skip silence option. It'd be nice to have this feature implemented.
